- hosts: all
  become: yes
  tasks: 
  - name: Install packages  
    ansible.builtin.apt:
      name: 
        - apache2
        - tree
        - unzip
      state: present
      update_cache: yes

  - name: Start packages
    ansible.builtin.service:
      name: [apache2, tree, unzip]
      state: started  
      enabled: yes   

  
    